# Generated by Django 5.2.9 on 2026-01-14 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/pdfs/'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='layout',
            field=models.CharField(choices=[('Two Column', 'Two Column'), ('Single Column', 'Single Column'), ('Sidebar Left', 'Sidebar Left'), ('Sidebar Right', 'Sidebar Right'), ('PDF Background', 'PDF Background')], default='Two Column', max_length=30),
        ),
        migrations.CreateModel(
            name='TemplatePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to='templates/pages/')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='users.resumetemplate')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('template', 'page_number')},
            },
        ),
    ]
