# Generated by Django 5.2.9 on 2026-01-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_resumetemplate_pdf_file_alter_resumetemplate_layout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumetemplate',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='layout',
            field=models.CharField(choices=[('Two Column', 'Two Column'), ('Single Column', 'Single Column'), ('Sidebar Left', 'Sidebar Left'), ('Sidebar Right', 'Sidebar Right')], default='Two Column', max_length=30),
        ),
        migrations.DeleteModel(
            name='TemplatePageImage',
        ),
    ]
